export default {
  auth: "/auth",
  organizations: "/organization",
  users: "/users",
  params: "/params",
  cameras: "/cameras",
  devices: "/devices",
  device: "/device/:id",
  goals: "/goals",
  goalList: "/goals/list",
  goalsStatistics: "/goals/statistics",
  goalAchieve: "/goals/achieve",
  achievedGoals: "/goals/achievedGoals",
  applications: "/applications",
  statistics: "/statistics",
  monitoring: "/statistics/monitoring",
  reports: "/statistics/reports/:reportName",
  docs: "/docs",
};
